name: App Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './app/src-tauri -> target'

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install frontend deps
        working-directory: ./app
        run: npm install

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./app
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
